CREATE TABLE race_bookmarks (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  external_race_id VARCHAR(100) DEFAULT NULL,
  race_name VARCHAR(255) NOT NULL,
  race_date DATE DEFAULT NULL,
  race_type VARCHAR(50) DEFAULT NULL,
  city VARCHAR(100) DEFAULT NULL,
  state VARCHAR(100) DEFAULT NULL,
  race_url VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
