CREATE TABLE group_events (
  id BIGINT NOT NULL AUTO_INCREMENT,
  creator_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  sport_type VARCHAR(50) NOT NULL DEFAULT 'RUN',
  event_datetime DATETIME NOT NULL,
  location_name VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE group_event_invites (
  id BIGINT NOT NULL AUTO_INCREMENT,
  event_id BIGINT NOT NULL,
  invitee_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
