CREATE TABLE live_shares (
  id BIGINT NOT NULL AUTO_INCREMENT,
  token CHAR(36) NOT NULL,
  user_id BIGINT NOT NULL,
  display_name VARCHAR(100) DEFAULT NULL,
  sport_type VARCHAR(50) DEFAULT 'RUN',
  lat DOUBLE DEFAULT NULL,
  lng DOUBLE DEFAULT NULL,
  elapsed_seconds INT DEFAULT 0,
  distance_meters INT DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  started_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_token (token)
);
