ALTER TABLE users ADD COLUMN whoop_access_token TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN whoop_refresh_token TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN whoop_token_expires_at BIGINT DEFAULT NULL;
ALTER TABLE users ADD COLUMN whoop_oauth_state VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN whoop_user_id BIGINT DEFAULT NULL;
ALTER TABLE users ADD COLUMN whoop_last_sync DATETIME DEFAULT NULL;
