ALTER TABLE users
  ADD COLUMN oura_access_token TEXT DEFAULT NULL,
  ADD COLUMN oura_refresh_token TEXT DEFAULT NULL,
  ADD COLUMN oura_token_expires_at BIGINT DEFAULT NULL,
  ADD COLUMN oura_oauth_state VARCHAR(255) DEFAULT NULL,
  ADD COLUMN oura_last_sync TIMESTAMP DEFAULT NULL;

ALTER TABLE activities
  MODIFY COLUMN source ENUM('MANUAL', 'INTEGRATION', 'GARMIN', 'STRAVA', 'APPLE_WATCH', 'COROS', 'APPLE_HEALTH', 'WHOOP', 'OURA') DEFAULT 'MANUAL';
